version: "3.3" 

volumes:
  lila_mongo:
    driver: local

services: 
  redis:
    image: redis:6-alpine
    container_name: lila_redis
    restart: always

  db:
    build: ./lila_db
    container_name: lila_db
    volumes:
      - .:/host
      - lila_mongo:/data/db
    restart: always
  
#  mongoexpress:
#    image: mongo-express
#    container_name: lila_mongoexpress
#    depends_on:
#      - db
#    links:
#      - db:db
#    environment:
#      - ME_CONFIG_MONGODB_SERVER=db
#      - ME_CONFIG_MONGODB_AUTH_DATABASE=lichess
#    ports: 
#      - 8081:8081
#    restart: always

  lila: 
     build: ./lila
     container_name: lila
     depends_on: 
       - db
       - redis
     links:
       - db:db
       - redis:redis
     volumes:
       - ./lila/data:/data
     ports: 
       - 9663:9663
     restart: always

  lila_ws:
     build: ./lila_ws
     container_name: lila_ws
     depends_on: 
       - db
       - redis
     links:
       - db:db
       - redis:redis
     ports:
       - 9664:9664
     volumes:
       - ./lila_ws/data:/data
     restart: always
